name       : haskell-retry
version    : 0.7.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/retry-0.7.4.2/retry-0.7.4.2.tar.gz : 521b392570b37b17ac8aaea2586a0a16a578f56b9cd0bbf69813b35f7ed2b47c
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
description: |
    This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-exceptions
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
