name       : haskell-retry
version    : 0.7.6.2
release    : 2
source     :
    - https://hackage.haskell.org/package/retry-0.7.6.2/retry-0.7.6.2.tar.gz : 4d99f0598762de530200477efdba80a51cde2316a698a64f8683b86ba0b8b92e
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
description: |
    This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class
    - haskell-exceptions
    - haskell-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
