name       : haskell-retry
version    : 0.8.1.2
release    : 3
source     :
    - https://hackage.haskell.org/package/retry-0.8.1.2/retry-0.8.1.2.tar.gz : c5415ed7928d81611fa570fef9dd6c009f3d722a16a36f1177bdde2e888e9e5b
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
description: |
    This package exposes combinators that can wrap arbitrary monadic actions. They run the action and potentially retry running it with some configurable delay for a configurable number of times.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
